backbone:
  model_type: 'vae_kl'
  embed_dim: 16
  ch_mult: [1, 1, 2, 2, 4]
  stride: 16
  ckpt_path: './weights/vae/kl16.ckpt'
data:
  dataset_name: 'mvtec_ad'
  category: 'grid'
  data_root: 'data/mvtec_ad'
  num_normal_samples: -1
  multi_category: false
  train: true
  batch_size: 8
  img_size: 224
  transform_type: 'default'
  num_workers: 1
  pin_memory: true
  mask: 
    strategy: 'random'
    ratio: 0.75
mim:
  model_type: 'mim_base'
  in_channels: 16
  patch_size: 1
  in_resolution: 14
  ema_decay: 0.999
  ckpt_path: null
optimizer:
  optimizer_name: 'adamw'
  start_lr: 0.0002
  max_lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.04
  scheduler_type: 'warmup_cosine'
  warmup_epochs: 40
  num_epochs: 2000
  grad_clip: 0.0
logging:
  log_interval: 10
  save_interval: 10
  save_images: false
  save_dir: 'results/ad_mim_base_long/grid'
meta:
  seed: 42
  device: 'cuda'
