backbone:
  model_type: 'vae_kl'
  embed_dim: 16
  ch_mult: [1, 1, 2, 2, 4]
  stride: 16
  ckpt_path: './weights/vae/kl16.ckpt'
data:
  dataset_name: 'mvtec_ad'
  exclude_class: 'bottle'
  data_root: 'data/mvtec_ad'
  num_normal_samples: -1
  multi_category: false
  train: true
  batch_size: 8
  img_size: 224
  transform_type: 'default'
  num_workers: 1
  pin_memory: true
  mask: 
    strategy: 'random'
    ratio: 0.75
    min_ratio: 0.75
    max_ratio: 0.75
diffusion:
  conditioning_scheme: 'cross_attention'
  model_type: 'icldit'
  num_classes: 15
  learn_sigma: false
  patch_size: 1
  num_heads: 8
  mlp_ratio: 4
  class_dropout_prob: 0.0
  target_channels: 3
  z_channels: 16
  depth: 4
  width: 256
  num_sampling_steps: '100'
  grad_checkpoint: false
  num_repeat: 1
encoder:
  num_patches: 196
  in_channels: 16
  num_blocks: 4
  embed_dim: 256
  num_heads: 8
  num_context_tokens: 20
  out_channels: 16
optimizer:
  optimizer_name: 'adamw'
  start_lr: 0.0002
  max_lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.000001
  scheduler_type: 'warmup_cosine'
  warmup_epochs: 10
  num_epochs: 200
  grad_clip: 1.0
logging:
  log_interval: 10
  save_interval: 10
  save_images: false
  save_dir: 'results/exp_icl_ca_vae_exbottle_enc'
meta:
  seed: 42
  device: 'cuda'
