backbone:
  model_type: 'vae_kl'
  embed_dim: 16
  ch_mult: [1, 1, 2, 2, 4]
  stride: 16
  ckpt_path: './weights/vae/kl16.ckpt'
data:
  dataset_name: 'mvtec_loco'
  category: 'screw_bag'
  data_root: 'data/mvtec_loco'
  num_normal_samples: -1
  multi_category: false
  train: true
  batch_size: 8
  img_size: 448
  transform_type: 'default'
  num_workers: 1
  pin_memory: true
  mask: 
    strategy: 'random'
    ratio: 0.75
    min_ratio: 0.3
    max_ratio: 0.75
mim:
  model_type: 'mim_base'
  in_channels: 16
  out_channels: 256
  patch_size: 1
  in_resolution: 28
  ema_decay: 0.999
  ckpt_path: null
  shortcut: true
diffusion:
  conditioning_scheme: 'cross_attention'
  model_type: 'dit'
  num_classes: 15
  learn_sigma: false
  patch_size: 1
  num_heads: 8
  mlp_ratio: 4
  class_dropout_prob: 0.0
  target_channels: 3
  z_channels: 16
  depth: 8
  width: 512
  num_sampling_steps: '100'
  grad_checkpoint: false
  num_repeat: 1
optimizer:
  optimizer_name: 'adamw'
  start_lr: 0.0002
  max_lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.000001
  scheduler_type: 'warmup_cosine'
  warmup_epochs: 40
  num_epochs: 4000
  grad_clip: 1.0
logging:
  log_interval: 10
  save_interval: 500
  save_images: false
  save_dir: 'results/ad_emar_ca_base_vae_loco_enc_id_big/screw_bag'
meta:
  seed: 42
  device: 'cuda'
