backbone:
  model_type: 'efficientnet-b4'
  embed_dim: 272
  outblocks: [1, 5, 9, 21]
  outstrides: [2, 4, 8, 16]
  pretrained: true
  stride: 16
data:
  dataset_name: 'mvtec_ad'
  category: 'hazelnut'
  data_root: 'data/mvtec_ad'
  num_normal_samples: -1
  multi_category: false
  train: true
  batch_size: 8
  img_size: 224
  transform_type: 'default'
  num_workers: 1
  pin_memory: true
  mask: 
    strategy: 'random'
    ratio: 0.75
    min_ratio: 0.75
    max_ratio: 0.75
    schedule: 'const'
mim:
  model_type: 'mim_base'
  in_channels: 272
  out_channels: 272
  patch_size: 1
  in_resolution: 14
  ema_decay: 0.999
  ckpt_path: null
  shortcut: true
diffusion:
  conditioning_scheme: 'cross_attention'
  model_type: 'dit'
  num_classes: 15
  learn_sigma: false
  patch_size: 1
  num_heads: 8
  mlp_ratio: 4
  class_dropout_prob: 0.0
  target_channels: 3
  z_channels: 272
  depth: 4
  width: 256
  num_sampling_steps: '100'
  grad_checkpoint: false
  num_repeat: 1
optimizer:
  optimizer_name: 'adamw'
  start_lr: 0.0002
  max_lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.000001
  scheduler_type: 'warmup_cosine'
  warmup_epochs: 40
  num_epochs: 2000
  grad_clip: 1.0
logging:
  log_interval: 10
  save_interval: 10
  save_images: false
  save_dir: 'results/emar_ca_base_enet_ad_enc_id/hazelnut'
meta:
  seed: 42
  device: 'cuda'
