diffusion:
  model_type: 'dit'
  num_classes: 15
  target_channels: 16
  z_channels: 768
  depth: 8
  width: 768
  num_sampling_steps: '100'
  ema_decay: 0.999
  grad_checkpoint: false
  patch_size: 1
vae:
  model_type: 'vae_kl'
  embed_dim: 16
  ch_mult: [1, 1, 2, 2, 4]
  stride: 16
  ckpt_path: './weights/vae/kl16.ckpt'
data:
  batch_size: 8
  category: splicing_connectors
  data_root: data/mvtec_loco
  dataset_name: mvtec_loco
  img_size: 448
  multi_category: false
  num_normal_samples: -1
  num_workers: 1
  pin_memory: true
  train: true
  transform_type: default
optimizer:
  grad_clip: 1.0
  max_lr: 0.001
  min_lr: 0.000001
  num_epochs: 2000
  optimizer_name: 'adamw'
  scheduler_type: 'warmup_cosine'
  start_lr: 0.0002
  warmup_epochs: 40
  weight_decay: 0.000001
logging:
  log_interval: 10
  save_interval: 10
  save_images: false
  save_dir: 'results/loco_dit_vae_448/splicing_connectors'
meta:
  seed: 42
  device: 'cuda'
