_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
data:
    value:
        batch_size: 8
        category: leather
        data_root: data/mvtec_ad
        dataset_name: mvtec_ad
        img_size: 224
        multi_category: false
        num_normal_samples: -1
        num_workers: 1
        pin_memory: true
        train: true
        transform_type: default
diffusion:
    value:
        depth: 8
        ema_decay: 0.999
        grad_checkpoint: false
        model_type: dit
        num_classes: 15
        num_sampling_steps: "100"
        patch_size: 1
        target_channels: 3
        width: 768
        z_channels: 16
logging:
    value:
        log_interval: 10
        save_dir: results/exp_dit_vae_ad/leather
        save_images: false
        save_interval: 10
meta:
    value:
        device: cuda
        seed: 42
optimizer:
    value:
        grad_clip: 1
        max_lr: 0.001
        min_lr: 1e-06
        num_epochs: 2000
        optimizer_name: adamw
        scheduler_type: warmup_cosine
        start_lr: 0.0002
        warmup_epochs: 40
        weight_decay: 1e-06
vae:
    value:
        ch_mult:
            - 1
            - 1
            - 2
            - 2
            - 4
        ckpt_path: ./weights/vae/kl16.ckpt
        embed_dim: 16
        model_type: vae_kl
        stride: 16
