backbone:
  ch_mult:
  - 1
  - 1
  - 2
  - 2
  - 4
  ckpt_path: ./weights/vae/kl16.ckpt
  embed_dim: 16
  model_type: vae_kl
  stride: 16
data:
  batch_size: 8
  category: bottle
  data_root: data/mvtec_ad
  dataset_name: mvtec_ad
  img_size: 224
  mask:
    ratio: 0.75
    strategy: random
  multi_category: false
  num_normal_samples: -1
  num_workers: 1
  pin_memory: true
  train: true
  transform_type: default
logging:
  log_interval: 10
  save_dir: ad_mim_base/bottle
  save_images: false
  save_interval: 10
meta:
  device: cuda
  seed: 42
mim:
  ckpt_path: null
  ema_decay: 0.999
  in_channels: 16
  in_resolution: 14
  model_type: mim_base
  patch_size: 1
optimizer:
  grad_clip: 1.0
  max_lr: 0.01
  min_lr: 0
  num_epochs: 200
  optimizer_name: adamw
  scheduler_type: cosine
  start_lr: 0.001
  warmup_epochs: 0
  weight_decay: 1.0e-06
