backbone:
  model_type: 'vae_kl'
  embed_dim: 16
  ch_mult: [1, 1, 2, 2, 4]
  stride: 16
  ckpt_path: './weights/vae/kl16.ckpt'
data:
  dataset_name: 'mvtec_ad'
  category: 'carpet'
  data_root: 'data/mvtec_ad'
  num_normal_samples: -1
  multi_category: false
  train: true
  batch_size: 8
  img_size: 224
  transform_type: 'default'
  num_workers: 1
  pin_memory: true
  mask: 
    strategy: 'random'
    ratio: 0.75
mim:
  model_type: 'mim_base'
  in_channels: 16
  patch_size: 1
  in_resolution: 14
  mim_loss_weight: 0
  diff_loss_weight: 1.0
  ema_decay: 0.999
  ckpt_path: null
diffusion:
  conditioning_scheme: 'cross_attention'
  model_type: 'dit'
  num_classes: 15
  learn_sigma: false
  patch_size: 1
  num_heads: 8
  mlp_ratio: 4
  class_dropout_prob: 0.0
  target_channels: 3
  z_channels: 768
  depth: 8
  width: 768
  num_sampling_steps: '100'
  grad_checkpoint: false
optimizer:
  optimizer_name: 'adamw'
  start_lr: 0.001
  max_lr: 0.01
  min_lr: 0
  weight_decay: 0.000001
  scheduler_type: 'cosine'
  warmup_epochs: 0
  num_epochs: 200
  grad_clip: 1.0
logging:
  log_interval: 10
  save_interval: 10
  save_images: false
  save_dir: 'ad_mar_ca_base/carpet'
meta:
  seed: 42
  device: 'cuda'
