diffusion:
  model_type: 'dit'
  conditioning_scheme: 'none'
  num_classes: 15
  target_channels: 16
  z_channels: 16
  depth: 4
  width: 256
  num_sampling_steps: '100'
  ema_decay: 0.999
  learn_sigma: false
  grad_checkpoint: false
  patch_size: 1
  num_heads: 8
  mlp_ratio: 4
  channel_mult: [1,1,2,2]
vae:
  model_type: 'vae_kl'
  embed_dim: 16
  ch_mult: [1, 1, 2, 2, 4]
  stride: 16
  ckpt_path: './weights/vae/kl16.ckpt'
data:
  batch_size: 8
  category: tile
  data_root: data/mvtec_ad
  dataset_name: mvtec_ad
  img_size: 256
  multi_category: false
  num_normal_samples: -1
  num_workers: 1
  pin_memory: true
  train: true
  transform_type: default
optimizer:
  grad_clip: 1.0
  init_lr: 0.0002
  peak_lr: 0.001
  final_lr: 0.000001
  num_epochs: 2000
  optimizer_name: adamw
  scheduler_type: warmup_cosine
  warmup_epochs: 40
  weight_decay: 0.000001
logging:
  log_interval: 10
  save_interval: 100
  save_images: false
  save_dir: 'results/exp_dit_feature_d4w256_lr/tile'
evaluation:
  eval_interval: 50
  start_step: 8
meta:
  seed: 42
  device: 'cuda'
